### ISSUE TITLE
Occasional small random string of characters when retrieving demos

### ISSUE THREAD

**Issue by obla** [ozfortress/booker-bot#1]
i.e.
Found 1 users for 'hertz' (9#<):
Found 1 users for 'brion' (P怀):

**Comment by BenjaminSchaaf** [comment]
Now coded names won't show unless users are found with the decoded name.

**Comment by thepparker** [comment]
Note that this is a symptom of converting the base32 string to lower case and, in conversion for demos, converting back to uppercase before decoding since sometimes named can be decoded without error. Usually it results in useless garbage as reported
