### ISSUE TITLE
Send demos link alongside server string when booking

### ISSUE THREAD

**Issue by BenjaminSchaaf** [ozfortress/booker-bot#2]
Makes it easier for people to quickly access demos after they've finished playing

**Comment by obla** [comment]
Or more so unbooking?

**Comment by BenjaminSchaaf** [comment]
Most people don't unbook (including myself) since there's usually servers available and they time out after 15 minutes anyway

**Comment by obla** [comment]
Fair.

**Comment by obla** [comment]
Nice!
